### ISSUE TITLE
Conflict with double doots

### ISSUE THREAD

**Issue by carc1n0gen** [Oth3r/Sit#10]
When both this sit mod and double doors mod are installed, doors cannot be opened without holding shift

**Comment by Oth3r** [comment]
what version, and which double door mod?
also is there anything changed in the Sit! config?

**Comment by carc1n0gen** [comment]
https://modrinth.com/mod/double-doors

minecraft v1.21

**Comment by Oth3r** [comment]
fixed in beta1.2.0.3
