### ISSUE TITLE
Crash while trying to sit

### ISSUE THREAD

**Issue by Maki-13** [Oth3r/Sit#12]
When I enter the game and try to sit down, the game freezes and crashes

### Put here any screenshots or videos (optional)
[2024-08-17-7.log](https://github.com/user-attachments/files/16645313/2024-08-17-7.log)
[crash-2024-08-17_17.49.49-client.txt](https://github.com/user-attachments/files/16645314/crash-2024-08-17_17.49.49-client.txt)

**Comment by Oth3r** [comment]
i see, its a crash with the C2ME mod, will try to have it fixed by next beta

**Comment by Oth3r** [comment]
fixed in b1.2.0.4
