### ISSUE TITLE
Text display not showing with Sit!

### ISSUE THREAD

**Issue by Longie520** [Oth3r/Sit#14]
### Describe your issue

Text displays (minecraft:text_display) do not show when Sit! is installed

### Steps to reproduce

1. Install latest FAPI and Sit! beta for 1.21.1
2. Log onto a server with text displays (in my case, windcraft.top) or summon a text display in a singleplayer world
3. It doesn't show

### What was the expected result?

Render the text display properly with Sit! installed

### Put here any screenshots or videos (optional)

With Sit!
![With Sit!](https://github.com/user-attachments/assets/a3535f90-1752-4970-b44d-7a50e2fc9bf9)

Without Sit!
![Without Sit!](https://github.com/user-attachments/assets/e2a1f129-3ad5-4cf9-b7da-13f9e67f5911)

Log file when with Sit!
[latest.log](https://github.com/user-attachments/files/17183376/latest.log)

**Comment by Oth3r** [comment]
fixed in beta1.2.0.7
