### ISSUE TITLE
Permission for use of code? (not an issue (there is no other tag))

### ISSUE THREAD

**Issue by ButterKing-28** [Oth3r/Sit#2]
Hello, I am currently making a PRIVATE mod that I am just playing on a server with my friends and I am wondering if I would be able to use your code if I give credit in the class(es)? Like I mentioned this mod is going to be private between my 2 friends and 1 brother on a server. I wanted to put it in my mod so they don't have to download a whole mod. Also, I find it interesting to deconstruct code to see how it works. If not that is ok.

Just let me know. : )
Thank you for your  consideration,
ButterKing-28

**Comment by ButterKing-28** [comment]
Nm, might as well put it on the server and have them download it.
sorry

**Comment by Oth3r** [comment]
also, its a server side mod, so the players don't need to download it for it to work :)

**Comment by ButterKing-28** [comment]
> also, its a server side mod, so the players don't need to download it for it to work :)

whattttt : 0
epic, thank you!
