### ISSUE TITLE
Custom blocks settings crashes minecraft entirely

### ISSUE THREAD

**Issue by Tanjiraaaaa** [Oth3r/Sit#3]
I added minecraft:spruce_log as one of the custom blocks in the settings and turned the custom block status to TRUE
Firstly, the custom blocks I added in the whitelist doesn't save after I rejoin (haven't tested the blacklist)
Secondly, trying to sit on the custom block with the custom block status as TRUE completely crashes minecraft
Here are the [logs](https://pastes.dev/IwiyPUaQSs)

**Comment by Tanjiraaaaa** [comment]
@Oth3r

**Comment by Oth3r** [comment]
how did you enter the new block?
also looking into the crash, should be fixed in the beta but its not gonna be out for 1.20.6 for a while

**Comment by Tanjiraaaaa** [comment]
> how did you enter the new block? also looking into the crash, should be fixed in the beta but its not gonna be out for 1.20.6 for a while

I clicked the plus button, typed "minecraft:spruce_log" and then saved changes I think
After that I just clicked done to get out of the menu
I modified the settings through modmenu btw

**Comment by Oth3r** [comment]
ahh i see, the crashing is a modmenu issue

when you enter custom blocks you need to also add the height and dismount height for the block, so something like "minecraft:spruce_log|1|1" would work for you

**Comment by Oth3r** [comment]
fixed in 5fff368

**Comment by Tanjiraaaaa** [comment]
Wait has the crashing been fixed too?
Because it crashed when I try to sit on the custom block

**Comment by Oth3r** [comment]
yea 👍

**Comment by Tanjiraaaaa** [comment]
> yea 👍

Thank you!!

**Comment by Oth3r** [comment]
just update to 1.1.8 when it comes out to get rid of the crashing bug
