### ISSUE TITLE
Cannot use the same Block Twice in Custom Blocks

### ISSUE THREAD

**Issue by curtonius** [Oth3r/Sit#4]
I am trying to do two sit states for Oak Trapdoors, one for trapdoors that are the Top half and one for the Bottom half.

`minecraft:oak_trapdoor|1|1|waterlogged=false,open=false,half=top`
and
`minecraft:oak_trapdoor|0.25|1|waterlogged=false,open=false,half=bottom`

However, the mod only detects one of these and not the other. I'm assuming it's because they are BOTH minecraft:oak_trapdoor and it's just their block states that are different

**Comment by Oth3r** [comment]
I see, thanks for the report! Probably will be fixed in the beta first before coming to a release in the future.

**Comment by Oth3r** [comment]
correction: already fixed in beta
