### ISSUE TITLE
Data.getServer() crashes when called on client.

### ISSUE THREAD

**Issue by theendercore** [Oth3r/Sit#6]
Minecraft : 1.21
Fabric Loader : 0.16.0 
Fapi : 0.100.7
For some reason, "Data.getServer()" gets called on client and then crashes because it's null.

Here is the crash log:
https://mclo.gs/vScChdX

This is not a very consistent bug, but it does happen.
I would recommend annotation `Data.getServer()` with nullable to prevent things like this from happening in the future

**Comment by Oth3r** [comment]
will be fixed in next beta, thanks for the report!
