### ISSUE TITLE
1.21 crash issue

### ISSUE THREAD

**Issue by Tanjiraaaaa** [Oth3r/Sit#7]
Crashes when trying to sit on custom blocks again
https://mclo.gs/y7dMOWl
It seems that whenever the game boots, all custom blocks are deleted and instead turned into "null"

**Comment by Tanjiraaaaa** [comment]
Same with when the config reloads

**Comment by Tanjiraaaaa** [comment]
https://mclo.gs/DGC9mXw config

**Comment by Oth3r** [comment]
what does the config look like before the crash?

**Comment by Tanjiraaaaa** [comment]
![image](https://github.com/user-attachments/assets/f1e14cc6-5d01-4c0e-9a8f-d66590da9682)
This is what the config looks like before it crashes

**Comment by Oth3r** [comment]
i see, the beta uses a new system for custom blocks, this is what it looks like
![image](https://github.com/user-attachments/assets/957dd42f-0ae0-4af7-b394-7458ed8e95e0)

```json
{
      "block-ids": [],
      "block-tags": [
        "#minecraft:logs"
      ],
      "blockstates": [
      ],
      "sittingHeight": 1.0
    }
```

in the next beta, i'll add default custom block entries to make it easier to add your own 😅
ill also fix the crashing, and when the update is out of beta, there should hopefully be documentation or a video explaining the new config system!

**Comment by Oth3r** [comment]
fixed in beta1.2.0.2
