### ISSUE TITLE
sit-while-seated doesnt remove sit entities when changing seats

### ISSUE THREAD

**Issue by Vaskyy** [Oth3r/Sit#9]
After a carpet spam sit session which was very fun, we've ended up with that:

![Screenshot 2024-08-11 194057](https://github.com/user-attachments/assets/fe587cc6-d0d3-46c2-9611-77a013b0979b)
![Screenshot 2024-08-11 194234](https://github.com/user-attachments/assets/65c8fef1-8a13-4d8a-a4a9-9ff7822537df)
![Screenshot 2024-08-11 194109](https://github.com/user-attachments/assets/36afaa28-0fcd-4347-b6b8-a9918feb4a6f)

sit seems to create entities..
until now it didnt lag at all..
but still is a bit.. annoying to see that on the minimap also.

**Comment by Oth3r** [comment]
ah, they're supposed to be removed automatically, what version are you running?
do /sit purgeChairEntities to see if they get removed that way

**Comment by Vaskyy** [comment]
![image](https://github.com/user-attachments/assets/cf887f9e-a447-446c-8bed-0f9b405778ab)
sit!-1.2.0.0+1.21.jar

command worked, entities gone

**Comment by Oth3r** [comment]
there's been 2 more beta updates since that one, i recommend trying that out and seeing if the bug still persists, + ill do some testing on my side of things

you can also switch to a stable version instead of the beta, if you aren't using any of the new features

**Comment by Oth3r** [comment]
fixed in b1.2.0.4
